name: Run Chunk Splitter

on: 
  workflow_dispatch
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: checkout all the submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install Requirements
      run: pip install pillow requests
      
