name: Run Chunk Splitter

on:
  schedule:
    - cron: "0,6,12,18,24,30,36,42,48,54 * * * *"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: checkout all the submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install Requirements
      run: pip install pillow requests
      
