name: Run Chunk Splitter

on: 
  workflow_dispatch:
  schedule:
  - cron: 30 * * * *
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: checkout all the submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install Requirements
      run: pip install pillow requests
    - name: Crawl and Split
      run: python chunk-split.py
    - name: Clean and Git actions
      run:  |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        rm -fv images/*.png
        git add images/
        git commit -m "crawl and split [skip ci]" || echo "No changes"
        git push
